# Generated by Django 5.2.4 on 2025-08-28 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest_id', models.IntegerField()),
                ('index', models.CharField(max_length=5)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, choices=[('dp', 'Dynamic Programming'), ('greedy', 'Greedy'), ('math', 'Math'), ('graphs', 'Graphs'), ('trees', 'Trees'), ('implementation', 'Implementation'), ('strings', 'Strings'), ('brute_force', 'Brute Force'), ('sortings', 'Sortings'), ('binary_search', 'Binary Search'), ('number_theory', 'Number Theory'), ('combinatorics', 'Combinatorics'), ('geometry', 'Geometry'), ('bitmasks', 'Bitmasks'), ('probabilities', 'Probabilities'), ('dsu', 'DSU'), ('constructive', 'Constructive'), ('two_pointers', 'Two Pointers')], max_length=50, null=True)),
            ],
            options={
                'unique_together': {('contest_id', 'index')},
            },
        ),
        migrations.CreateModel(
            name='SeenProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
